# Generated by Django 5.0.6 on 2024-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicationcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcomment',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
