# Generated by Django 5.0.6 on 2024-08-25 08:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_publication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='shorts_description_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='кротький описание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='shorts_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='кротький описание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
